import './style.css'
// import example from './exmaples/01_meshbasicmaterial'
// import example from './exmaples/02_lambert-phong'
// import example from './exmaples/03_meshstandard'
// import example from './exmaples/04_side'
// import example from './exmaples/05_texture-load'
// import example from './exmaples/06_loading-manager'
// import example from './exmaples/07_texture-transform'
// import example from './exmaples/08_multiple-face-cube'
// import example from './exmaples/09_meshtoon'
// import example from './exmaples/10_meshnormal'
// import example from './exmaples/11_meshmatcap'
// import example from './exmaples/12_effect-meshstandardmaterial'
// import example from './exmaples/13_envmap'
// import example from './exmaples/14_skybox'
import example from './exmaples/15_skybox-envmap'

example()
